apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: sample-app
  namespace: sample-app
  labels:
    app.kubernetes.io/name: sample-app
spec:
  gatewayClassName: eg
  listeners:
    - name: http
      protocol: HTTP
      port: 80
      hostname: sample-app.local
      allowedRoutes:
        namespaces:
          from: Same
